-- tipe: [ video, image, document ]
-- tags: [ carousel, external-web, related-web, zona-integritas, agen-perubahan, 
--          info-publik, brosur, youtube, pengumuman, contact ]
create table media (
  id integer primary key generated by default as identity,
  tipe text,
  url text,
  tags text[],
  metadata jsonb,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now()
);

-- tags: [ news, pengumuman, info-publik ]
-- status: [ published, draft ]
create table article (
  id integer primary key generated by default as identity,
  title text,
  description text,
  status text,
  content jsonb,
  tags text[],
  avatar text,
  medias text[],
  created_at timestamp not null default now(),
  updated_at timestamp not null default now()
);

create table sidang (
  id integer primary key generated by default as identity,
  nomor text not null,
  waktu timestamp not null,
  ruangan text not null,
  penggugat text[] not null,
  tergugat text[] not null,
  agenda text,
  metadata jsonb
);

create table "users" (
  id integer primary key generated by default as identity,
  username text,
  password_hash text
);

create index idx_penggugat_sidang on sidang using GIN("penggugat");
create index idx_tergugat_sidang on sidang using GIN("tergugat");
create index idx_tags_article on article using GIN("tags");
create index idx_tags_article on article using GIN("tags");
